// Top-level build file for Pixie Look FaceFocus Integration
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.20"
        classpath "com.google.dagger:hilt-android-gradle-plugin:2.48.1"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        // For libvlc AAR in local libs folder
        flatDir {
            dirs 'libs'
        }
    }
}
